//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.06 at 02:52:05 AM EEST 
//


package com.lawal.springcloud.eureka.model.xml;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="versions__delta" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="apps__hashcode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="application" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="instance" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="hostName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="app" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ipAddr" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="overriddenstatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="port">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>short">
 *                                     &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="securePort">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>short">
 *                                     &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="countryId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="dataCenterInfo">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="leaseInfo">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="renewalIntervalInSecs" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="durationInSecs" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="registrationTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="lastRenewalTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="evictionTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                       &lt;element name="serviceUpTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="metadata">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="instanceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="homePageUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="statusPageUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="healthCheckUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="vipAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="isCoordinatingDiscoveryServer" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *                             &lt;element name="lastUpdatedTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="lastDirtyTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                             &lt;element name="actionType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "versionsDelta",
    "appsHashcode",
    "application"
})
@XmlRootElement(name = "applications")
public class Applications {

    @XmlElement(name = "versions__delta")
    protected long versionsDelta;
    @XmlElement(name = "apps__hashcode", required = true)
    protected String appsHashcode;
    @XmlElement(required = true)
    protected List<Applications.Application> application;

    /**
     * Gets the value of the versionsDelta property.
     * 
     */
    public long getVersionsDelta() {
        return versionsDelta;
    }

    /**
     * Sets the value of the versionsDelta property.
     * 
     */
    public void setVersionsDelta(long value) {
        this.versionsDelta = value;
    }

    /**
     * Gets the value of the appsHashcode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppsHashcode() {
        return appsHashcode;
    }

    /**
     * Sets the value of the appsHashcode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppsHashcode(String value) {
        this.appsHashcode = value;
    }

    /**
     * Gets the value of the application property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the application property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplication().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Applications.Application }
     * 
     * 
     */
    public List<Applications.Application> getApplication() {
        if (application == null) {
            application = new ArrayList<Applications.Application>();
        }
        return this.application;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="instance" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="hostName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="app" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ipAddr" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="overriddenstatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="port">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>short">
     *                           &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="securePort">
     *                     &lt;complexType>
     *                       &lt;simpleContent>
     *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>short">
     *                           &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
     *                         &lt;/extension>
     *                       &lt;/simpleContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="countryId" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                   &lt;element name="dataCenterInfo">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="leaseInfo">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="renewalIntervalInSecs" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="durationInSecs" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="registrationTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="lastRenewalTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="evictionTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                             &lt;element name="serviceUpTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="metadata">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="instanceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="homePageUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="statusPageUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="healthCheckUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="vipAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="isCoordinatingDiscoveryServer" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
     *                   &lt;element name="lastUpdatedTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="lastDirtyTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
     *                   &lt;element name="actionType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "name",
        "instance"
    })
    @XmlRootElement(name = "application")
    public static class Application {

        @XmlElement(required = true)
        protected String name;
        @XmlElement(required = true)
        protected List<Applications.Application.Instance> instance;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the instance property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the instance property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getInstance().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Applications.Application.Instance }
         * 
         * 
         */
        public List<Applications.Application.Instance> getInstance() {
            if (instance == null) {
                instance = new ArrayList<Applications.Application.Instance>();
            }
            return this.instance;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="hostName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="app" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ipAddr" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="overriddenstatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="port">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>short">
         *                 &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="securePort">
         *           &lt;complexType>
         *             &lt;simpleContent>
         *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>short">
         *                 &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
         *               &lt;/extension>
         *             &lt;/simpleContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="countryId" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="dataCenterInfo">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *                 &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="leaseInfo">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="renewalIntervalInSecs" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="durationInSecs" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="registrationTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="lastRenewalTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="evictionTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                   &lt;element name="serviceUpTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="metadata">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="instanceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="homePageUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="statusPageUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="healthCheckUrl" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="vipAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="isCoordinatingDiscoveryServer" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
         *         &lt;element name="lastUpdatedTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="lastDirtyTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
         *         &lt;element name="actionType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "hostName",
            "app",
            "ipAddr",
            "status",
            "overriddenstatus",
            "port",
            "securePort",
            "countryId",
            "dataCenterInfo",
            "leaseInfo",
            "metadata",
            "homePageUrl",
            "statusPageUrl",
            "healthCheckUrl",
            "vipAddress",
            "isCoordinatingDiscoveryServer",
            "lastUpdatedTimestamp",
            "lastDirtyTimestamp",
            "actionType"
        })
        public static class Instance {

            @XmlElement(required = true)
            protected String hostName;
            @XmlElement(required = true)
            protected String app;
            @XmlElement(required = true)
            protected String ipAddr;
            @XmlElement(required = true)
            protected String status;
            @XmlElement(required = true)
            protected String overriddenstatus;
            @XmlElement(required = true)
            protected Applications.Application.Instance.Port port;
            @XmlElement(required = true)
            protected Applications.Application.Instance.SecurePort securePort;
            protected int countryId;
            @XmlElement(required = true)
            protected Applications.Application.Instance.DataCenterInfo dataCenterInfo;
            @XmlElement(required = true)
            protected Applications.Application.Instance.LeaseInfo leaseInfo;
            @XmlElement(required = true)
            protected Applications.Application.Instance.Metadata metadata;
            @XmlElement(required = true)
            protected String homePageUrl;
            @XmlElement(required = true)
            protected String statusPageUrl;
            @XmlElement(required = true)
            protected String healthCheckUrl;
            @XmlElement(required = true)
            protected String vipAddress;
            protected boolean isCoordinatingDiscoveryServer;
            protected long lastUpdatedTimestamp;
            protected long lastDirtyTimestamp;
            @XmlElement(required = true)
            protected String actionType;

            /**
             * Gets the value of the hostName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHostName() {
                return hostName;
            }

            /**
             * Sets the value of the hostName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHostName(String value) {
                this.hostName = value;
            }

            /**
             * Gets the value of the app property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getApp() {
                return app;
            }

            /**
             * Sets the value of the app property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setApp(String value) {
                this.app = value;
            }

            /**
             * Gets the value of the ipAddr property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIpAddr() {
                return ipAddr;
            }

            /**
             * Sets the value of the ipAddr property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIpAddr(String value) {
                this.ipAddr = value;
            }

            /**
             * Gets the value of the status property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatus() {
                return status;
            }

            /**
             * Sets the value of the status property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatus(String value) {
                this.status = value;
            }

            /**
             * Gets the value of the overriddenstatus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOverriddenstatus() {
                return overriddenstatus;
            }

            /**
             * Sets the value of the overriddenstatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOverriddenstatus(String value) {
                this.overriddenstatus = value;
            }

            /**
             * Gets the value of the port property.
             * 
             * @return
             *     possible object is
             *     {@link Applications.Application.Instance.Port }
             *     
             */
            public Applications.Application.Instance.Port getPort() {
                return port;
            }

            /**
             * Sets the value of the port property.
             * 
             * @param value
             *     allowed object is
             *     {@link Applications.Application.Instance.Port }
             *     
             */
            public void setPort(Applications.Application.Instance.Port value) {
                this.port = value;
            }

            /**
             * Gets the value of the securePort property.
             * 
             * @return
             *     possible object is
             *     {@link Applications.Application.Instance.SecurePort }
             *     
             */
            public Applications.Application.Instance.SecurePort getSecurePort() {
                return securePort;
            }

            /**
             * Sets the value of the securePort property.
             * 
             * @param value
             *     allowed object is
             *     {@link Applications.Application.Instance.SecurePort }
             *     
             */
            public void setSecurePort(Applications.Application.Instance.SecurePort value) {
                this.securePort = value;
            }

            /**
             * Gets the value of the countryId property.
             * 
             */
            public int getCountryId() {
                return countryId;
            }

            /**
             * Sets the value of the countryId property.
             * 
             */
            public void setCountryId(int value) {
                this.countryId = value;
            }

            /**
             * Gets the value of the dataCenterInfo property.
             * 
             * @return
             *     possible object is
             *     {@link Applications.Application.Instance.DataCenterInfo }
             *     
             */
            public Applications.Application.Instance.DataCenterInfo getDataCenterInfo() {
                return dataCenterInfo;
            }

            /**
             * Sets the value of the dataCenterInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link Applications.Application.Instance.DataCenterInfo }
             *     
             */
            public void setDataCenterInfo(Applications.Application.Instance.DataCenterInfo value) {
                this.dataCenterInfo = value;
            }

            /**
             * Gets the value of the leaseInfo property.
             * 
             * @return
             *     possible object is
             *     {@link Applications.Application.Instance.LeaseInfo }
             *     
             */
            public Applications.Application.Instance.LeaseInfo getLeaseInfo() {
                return leaseInfo;
            }

            /**
             * Sets the value of the leaseInfo property.
             * 
             * @param value
             *     allowed object is
             *     {@link Applications.Application.Instance.LeaseInfo }
             *     
             */
            public void setLeaseInfo(Applications.Application.Instance.LeaseInfo value) {
                this.leaseInfo = value;
            }

            /**
             * Gets the value of the metadata property.
             * 
             * @return
             *     possible object is
             *     {@link Applications.Application.Instance.Metadata }
             *     
             */
            public Applications.Application.Instance.Metadata getMetadata() {
                return metadata;
            }

            /**
             * Sets the value of the metadata property.
             * 
             * @param value
             *     allowed object is
             *     {@link Applications.Application.Instance.Metadata }
             *     
             */
            public void setMetadata(Applications.Application.Instance.Metadata value) {
                this.metadata = value;
            }

            /**
             * Gets the value of the homePageUrl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHomePageUrl() {
                return homePageUrl;
            }

            /**
             * Sets the value of the homePageUrl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHomePageUrl(String value) {
                this.homePageUrl = value;
            }

            /**
             * Gets the value of the statusPageUrl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getStatusPageUrl() {
                return statusPageUrl;
            }

            /**
             * Sets the value of the statusPageUrl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setStatusPageUrl(String value) {
                this.statusPageUrl = value;
            }

            /**
             * Gets the value of the healthCheckUrl property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHealthCheckUrl() {
                return healthCheckUrl;
            }

            /**
             * Sets the value of the healthCheckUrl property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHealthCheckUrl(String value) {
                this.healthCheckUrl = value;
            }

            /**
             * Gets the value of the vipAddress property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getVipAddress() {
                return vipAddress;
            }

            /**
             * Sets the value of the vipAddress property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setVipAddress(String value) {
                this.vipAddress = value;
            }

            /**
             * Gets the value of the isCoordinatingDiscoveryServer property.
             * 
             */
            public boolean isIsCoordinatingDiscoveryServer() {
                return isCoordinatingDiscoveryServer;
            }

            /**
             * Sets the value of the isCoordinatingDiscoveryServer property.
             * 
             */
            public void setIsCoordinatingDiscoveryServer(boolean value) {
                this.isCoordinatingDiscoveryServer = value;
            }

            /**
             * Gets the value of the lastUpdatedTimestamp property.
             * 
             */
            public long getLastUpdatedTimestamp() {
                return lastUpdatedTimestamp;
            }

            /**
             * Sets the value of the lastUpdatedTimestamp property.
             * 
             */
            public void setLastUpdatedTimestamp(long value) {
                this.lastUpdatedTimestamp = value;
            }

            /**
             * Gets the value of the lastDirtyTimestamp property.
             * 
             */
            public long getLastDirtyTimestamp() {
                return lastDirtyTimestamp;
            }

            /**
             * Sets the value of the lastDirtyTimestamp property.
             * 
             */
            public void setLastDirtyTimestamp(long value) {
                this.lastDirtyTimestamp = value;
            }

            /**
             * Gets the value of the actionType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getActionType() {
                return actionType;
            }

            /**
             * Sets the value of the actionType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActionType(String value) {
                this.actionType = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *       &lt;attribute name="class" type="{http://www.w3.org/2001/XMLSchema}string" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "name"
            })
            public static class DataCenterInfo {

                @XmlElement(required = true)
                protected String name;
                @XmlAttribute(name = "class")
                protected String clazz;

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the clazz property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getClazz() {
                    return clazz;
                }

                /**
                 * Sets the value of the clazz property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setClazz(String value) {
                    this.clazz = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="renewalIntervalInSecs" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="durationInSecs" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="registrationTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="lastRenewalTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="evictionTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *         &lt;element name="serviceUpTimestamp" type="{http://www.w3.org/2001/XMLSchema}long"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "renewalIntervalInSecs",
                "durationInSecs",
                "registrationTimestamp",
                "lastRenewalTimestamp",
                "evictionTimestamp",
                "serviceUpTimestamp"
            })
            public static class LeaseInfo {

                protected int renewalIntervalInSecs;
                protected int durationInSecs;
                protected long registrationTimestamp;
                protected long lastRenewalTimestamp;
                protected long evictionTimestamp;
                protected long serviceUpTimestamp;

                /**
                 * Gets the value of the renewalIntervalInSecs property.
                 * 
                 */
                public int getRenewalIntervalInSecs() {
                    return renewalIntervalInSecs;
                }

                /**
                 * Sets the value of the renewalIntervalInSecs property.
                 * 
                 */
                public void setRenewalIntervalInSecs(int value) {
                    this.renewalIntervalInSecs = value;
                }

                /**
                 * Gets the value of the durationInSecs property.
                 * 
                 */
                public int getDurationInSecs() {
                    return durationInSecs;
                }

                /**
                 * Sets the value of the durationInSecs property.
                 * 
                 */
                public void setDurationInSecs(int value) {
                    this.durationInSecs = value;
                }

                /**
                 * Gets the value of the registrationTimestamp property.
                 * 
                 */
                public long getRegistrationTimestamp() {
                    return registrationTimestamp;
                }

                /**
                 * Sets the value of the registrationTimestamp property.
                 * 
                 */
                public void setRegistrationTimestamp(long value) {
                    this.registrationTimestamp = value;
                }

                /**
                 * Gets the value of the lastRenewalTimestamp property.
                 * 
                 */
                public long getLastRenewalTimestamp() {
                    return lastRenewalTimestamp;
                }

                /**
                 * Sets the value of the lastRenewalTimestamp property.
                 * 
                 */
                public void setLastRenewalTimestamp(long value) {
                    this.lastRenewalTimestamp = value;
                }

                /**
                 * Gets the value of the evictionTimestamp property.
                 * 
                 */
                public long getEvictionTimestamp() {
                    return evictionTimestamp;
                }

                /**
                 * Sets the value of the evictionTimestamp property.
                 * 
                 */
                public void setEvictionTimestamp(long value) {
                    this.evictionTimestamp = value;
                }

                /**
                 * Gets the value of the serviceUpTimestamp property.
                 * 
                 */
                public long getServiceUpTimestamp() {
                    return serviceUpTimestamp;
                }

                /**
                 * Sets the value of the serviceUpTimestamp property.
                 * 
                 */
                public void setServiceUpTimestamp(long value) {
                    this.serviceUpTimestamp = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="instanceId" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "instanceId"
            })
            public static class Metadata {

                @XmlElement(required = true)
                protected String instanceId;

                /**
                 * Gets the value of the instanceId property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getInstanceId() {
                    return instanceId;
                }

                /**
                 * Sets the value of the instanceId property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setInstanceId(String value) {
                    this.instanceId = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>short">
             *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class Port {

                @XmlValue
                protected short value;
                @XmlAttribute
                protected Boolean enabled;

                /**
                 * Gets the value of the value property.
                 * 
                 */
                public short getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 */
                public void setValue(short value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the enabled property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public Boolean isEnabled() {
                    return enabled;
                }

                /**
                 * Sets the value of the enabled property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setEnabled(Boolean value) {
                    this.enabled = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;simpleContent>
             *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>short">
             *       &lt;attribute name="enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" />
             *     &lt;/extension>
             *   &lt;/simpleContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "value"
            })
            public static class SecurePort {

                @XmlValue
                protected short value;
                @XmlAttribute
                protected Boolean enabled;

                /**
                 * Gets the value of the value property.
                 * 
                 */
                public short getValue() {
                    return value;
                }

                /**
                 * Sets the value of the value property.
                 * 
                 */
                public void setValue(short value) {
                    this.value = value;
                }

                /**
                 * Gets the value of the enabled property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Boolean }
                 *     
                 */
                public Boolean isEnabled() {
                    return enabled;
                }

                /**
                 * Sets the value of the enabled property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Boolean }
                 *     
                 */
                public void setEnabled(Boolean value) {
                    this.enabled = value;
                }

            }

        }

    }

}
